name = "telecasts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = "public"

[[r2_buckets]]
binding = "BUCKET_RSS"
bucket_name = "rss"
preview_bucket_name = "rss-dev"

[[r2_buckets]]
binding = "BUCKET_THUMB" 
bucket_name = "thumb"
preview_bucket_name = "thumb-dev"
